name: CI

on: 
  push:
    branches: [main]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install          

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable

      - name: Build Python package
        run: poetry run maturin build --release --no-sdist --strip 

  python-publish:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install

      - name: Build Python package
        run: poetry run maturin build --release --no-sdist --strip 


      - name: PyPi publish
        # if: github.event_name == 'release' && github.event.action == 'created'
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI }}
        run: poetry run maturin publish --username __token__
