---
repos:
    - repo: https://github.com/ambv/black
      rev: 21.5b2
      hooks:
          - id: black
    - repo: https://gitlab.com/pycqa/flake8
      # flake8 version should match .travis.yml
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
                  - dlint # Check common security issues
                  - flake8-broken-line # Don't escape newlines. (surround in parens or simplify)
                  - flake8-debugger # Don't commit debugger calls
                  - flake8-executable # Check shebangs and executable permissions
                  - flake8-logging-format # Use log arguments, not string format
                  - flake8-pep3101 # Don't use old string % formatting
                  - flake8-pytest # Use plain assert, not unittest assertions
                  - pep8-naming # Follow pep8 naming rules (eg. function names lowercase)

