[tool.poetry]
name = "ycc"
version = "0.3"
description = ""
authors = ["神秘的·"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.x"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0","pdsystem"]
build-backend = "poetry.core.masonry.api"
