[tool.poetry]
name = "eyecu_pulsar"
version = "0.1.7"
description = "RTSP Sync Library"
authors = ["Oguz Vuruskaner <ovuruska@outlook.com>"]
license = "MIT"
repository = "https://github.com/eyecuvision/pulsar"
keywords = [
    "Video Streaming",
    "rtsp",
    "Open CV"
]

packages = [
    { include = "pulsar" }
]

[tool.poetry.dependencies]
python = "^3.6"
opencv-python = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
