[tool.poetry]
name = "ardkit"
version = "1.0.0"
description = "ardkit"
readme = "README.md"
homepage = "https://github.com/Ardustri/ardkit"
authors = ["Ardustri <contact@ardkit.netlify.app>"]
license = "GPL-3.0-or-later"
packages = [{include = "ardkit"}]
include = ["ardkit/utils/*"]

[tool.poetry.dependencies]
python = ">=3.7"


[tool.poetry.scripts]
ardkit = "ardkit.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"