variables:
  CIBW_BUILD: cp37-* cp38-* cp39-*
  CIBW_BEFORE_BUILD_LINUX: yum install -y geos-devel freetype-devel libpng-devel

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:
    default_python: '3.8'
    coverage: codecov

    libraries:
      yum:
        - geos-devel
        - freetype-devel
        - libpng-devel

    envs:

    - linux: codestyle

    - macos: py37-test-oldestdeps-cov
    - macos: py38-test-cov
    - macos: py39-test-cov

    - linux: py37-test-oldestdeps-cov
    - linux: py38-test-cov
    - linux: py39-test-cov

    - linux32: py37-test-oldestdeps-cov
    - linux32: py38-test-cov

    - windows: py37-test-oldestdeps-cov
    - windows: py38-test-cov
    - windows: py39-test-cov

    - macos: build_docs
    - linux: build_docs
    - macos: build_docs

- template: publish.yml@OpenAstronomy
  parameters:
    test_command: pytest -p no:warnings --pyargs reproject
    test_extras: test
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name : 'pypi_endpoint'
    targets:
    - sdist
    - wheels_linux
    - wheels_macos
    - wheels_windows
