from typing import Any, Sequence, Tuple
from vtelem.enums.frame import MessageType as MessageType
from vtelem.frame.framer import Framer as Framer
from vtelem.frame.message import MessageFrame as MessageFrame, frames_required as frames_required

class MessageFramer(Framer):
    message_numbers: Any
    def __init__(self, mtu: int, app_id_basis: float = ..., use_crc: bool = ...) -> None: ...
    def message_frame(self, time: float = ...) -> MessageFrame: ...
    def serialize_message(self, message: bytes, time: float = ..., message_type: MessageType = ...) -> Tuple[Sequence[MessageFrame], int]: ...
    def serialize_message_str(self, message: str, time: float = ..., message_type: MessageType = ...) -> Tuple[Sequence[MessageFrame], int]: ...
