from typing import Any

class LockEntity:
    lock: Any
    def __init__(self) -> None: ...

class TimeEntity(LockEntity):
    time: Any
    def __init__(self, init_time: float = ...) -> None: ...
    def advance_time(self, amount: float) -> None: ...
    def set_time(self, time: float) -> None: ...
    def get_time(self) -> float: ...
