---
#- debug:
#    var: robotframework_install

- name: Set Robot Framework install flag.
  set_fact:
    _robotframework_install: "{{ robotframework_install | bool }}"
  when:
    - robotframework_install is defined
    - robotframework_install != 'auto'

- name: Lookup Robot Framework install flag.
  set_fact:
    _robotframework_install: "{{ not (ansible_local.get('robotframework_installed', 'no') | bool) }}"
  when: _robotframework_install is undefined

#- debug:
#    var: _robotframework_install

- name: Ensure python pip is installed.
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/pip/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ role_path }}/tasks/pip/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ role_path }}/tasks/pip/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/tasks/pip/{{ ansible_os_family }}.yml"
    - "{{ role_path }}/tasks/pip/unknown.yml"
  when: _robotframework_install

- name: Install Robot Framework.
  become: yes
  pip:
    state: present
    name:
      # Install pyyaml so `robot` will support yaml format variable files.
      - pyyaml
      - "{{ robotframework_package_name }}{{ robotframework_package_version_spec }}"
  when: _robotframework_install

- name: Install Robot Framework Test Libraries.
  become: yes
  pip:
    state: present
    name: "{{ robotframework_external_libraries }}"
  when:
    - _robotframework_install
    - robotframework_external_libraries | count > 0

- name: Ensure facts directory exists.
  become: yes
  file:
    state: directory
    path: /etc/ansible/facts.d/

- name: Save Robot Framework installation facts.
  become: yes
  copy:
    content: '"yes"'
    dest: /etc/ansible/facts.d/robotframework_installed.fact
    mode: "644"
