[tool.poetry]
name = "dq_tool"
version = "0.0.4"
description = ""
readme = "README.md"
repository = "https://github.com/DataSentics/dq_tool"

authors = ["DataSentics <info@datasentics.com>"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

[tool.poetry.dependencies]
python = "^3.7"
great-expectations = "^0.13.0"
sqlalchemy = ">=1.3.16"


[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.7.0"
flake8 = "^3.8.4"
twine = "^3.3.0"
pytest-azurepipelines = "^0.8.0"
poethepoet = "^0.10.0"

[tool.poe.tasks]
pylint = "pylint dq_tool"
flake8 = "flake8"
pytest = "python -m pytest -v"
checkall = ["flake8", "pylint", "pytest"]
build = "poetry build"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
