[tool.poetry]
name = "sycc"
version = "0.5"
description = ""
authors = ["神秘的·"]
license = "MIT(not The original version)"

[tool.poetry.dependencies]
python = "3.x"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0","pdsystem"]
build-backend = "poetry.core.masonry.api"
