BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB


BBBBB BBBBBBBBBBBBBB
  

  XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Clear queue') XX
      XX XXXXXXXXX XXXXX XXXXXXXXXXXXXX
    XXXX
  XXXXX
BBBBBBBB


BBBBB BBBBBBBBBBBBB
  

  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXX XXXXXXXXXXXXXX
    XXXXXX gettext(u'Clear queue') XXXXXXX
  XXXX
BBBBBBBB
