BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB


BBBBB BBBBB
  

  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Clear queue') XX
    XX XXXXXXXXX XXXXX XXXXXXXXXXXXXX
  XXXX
BBBBBBBB
