[tool.poetry]
name = "checkpea"
version = "0.1.1"
description = "Checkpea tracks the state of your application."
authors = ["Dani Perez <daniel.perez@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
