[tool.poetry]
name = "pacmine"
version = "1.2.3"
description = "Simple package manager-esque mod manager for Minecraft"
authors = ["aidan <aidan.chaplin@gmail.com>"]
readme = "README.md"
homepage = "https://gitlab.com/TheBicameralMind/pacmine"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
tqdm = "^4.62.0"
Columnar = "^1.3.1"
arrow = "^1.1.1"
semantic-version = "^2.8.5"
termcolor = "^1.1.0"
fire = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
pacmine = 'pacmine.__main__:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
