GROUP_REFERENCE = {
    "^bds": "bất động sản",
    "^dtxd": "đầu tư xây dựng",
    "^thuongmai": "thương mại",
    "^dtpt": "đầu tư phát triển",
    "^vantai": "vận tải",
    "^nhua": "nhựa",
    "^sxkd": "sản xuất kinh doanh",
    "^thep": "thép",
    "^thuysan": "thuỷ sản",
    "^thucpham": "thực phẩm",
    "^khoangsan": "khoáng sản",
    "^xaydung": "xây dựng",
    "^hk": "hàng không",
    "^vlxd": "vật liệu xây dựng",
    "^daukhi": "dầu khí",
    "^dichvu": "dịch vụ",
    "^congnghe": "công nghệ",
    "^ck": "chứng khoán",
    "^caosu": "cao su",
    "^nangluong": "năng lượng",
    "^duocpham": "dược phẩm",
    "^phanbon": "phân bón",
    "^giaoduc": "giáo dục",
    "^dvci": "dịch vụ công ích",
    "^nganhang": "ngân hàng",
    "vn30": "vn30",
    "all": "tất cả",
    "etf": "etf",
}
