name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        conda create --yes --name TEST python=${{ matrix.python-version }} pip python-build --file requirements.txt --file requirements-dev.txt --channel conda-forge --strict-channel-priority
        source activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: Tarball tests
      shell: bash -l {0}
      run: |
        source activate TEST
        python setup.py --version
        python -m build --sdist --wheel . --outdir dist
        check-manifest --verbose
        twine check dist/*

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        pytest -n 2 -rxs --cov=gliderpy tests
