mlctl_version: 0.1
metadata:
  version: 1.0
  project: height_data
  job_name: sklearndemo
  job_type: train
env_vars:
  hp_eta: 0.3
  hp_max_depth: 3
  hp_objective: multi:softprob
  hp_num_class: 3
data:
  input: https://mlctldata.blob.core.windows.net/modeldata/data.csv