[tool.poetry]
name = "hypothesis-array-api"
version = "0.1.1"
description = "Hypothesis strategies for Array API libraries"
authors = ["Matthew Barber <quitesimplymatt@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/honno/hypothesis-array-api"
packages = [{include = "hypothesis_array.py"}]
classifiers = [
    "Framework :: Hypothesis"
]

[tool.poetry.dependencies]
python = "^3.7"
hypothesis = "^6.14.1"
sphinx = {version = "^3", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
numpy = "^1.21.0"
torch = "^1.9.0"
pre-commit = "^2.13.0"

[tool.poetry.extras]
docs = ["sphinx"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
