
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-16T16:38:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "258a47f6cbf75249c9d04468d1de6b70dbb038dd",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
