# @package _global_

# specify here default training configuration
defaults:
  - strict_config
  - scheduler: night
  - miner: eth
  - override hydra/job_logging: disabled

# everything below would override experiments configs! so take care
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  # don't create subdir for yaml files
  output_subdir: .