[tool.poetry]
name = "netbox-plugin-gpon"
version = "1.0.0"
description = "This package adds GPON OLTs, ONTs, and Splitter logic and database operations to Netbox."
homepage = "https://github.com/MajesticFalcon/netbox_plugin_gpon"
repository = "https://github.com/MajesticFalcon/netbox_plugin_gpon"
authors = ["sutley"]

packages = [
    { include = "netbox_plugin_gpon" },
]
[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^20.8b1"
invoke = "^1.5.0"
pylint = "^2.6.0"
pylint-django = "^2.4.2"
pydocstyle = "^5.1.1"
yamllint = "^1.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
