# Generated by Django 2.2.24 on 2021-08-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210801_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpass',
            old_name='password',
            new_name='passwordd',
        ),
    ]
