[tool.poetry]
name = "requests-base"
version = "0.1.1"
description = ""
authors = ["Michael Tinsley <michaeltinsley@outlook.com>"]
maintainers = ["Michael Tinsley <michaeltinsley@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/michaeltinsley/requests-base/"
repository = "https://github.com/michaeltinsley/requests-base/"
keywords = [
    "Requests",
    "API",
]

[tool.poetry.dependencies]
python = "^3.6.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
isort = "^5.9.2"
flake8 = "^3.9.2"
pylint = "^2.9.5"
black = "^21.7b0"
mkdocs-material = "^7.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"
