[tool.poetry]
name = "splitvid"
version = "0.1.0"
description = "Split videos with ffmpeg for a certain period"
authors = ["4thel00z <4thel00z@gmail.com>"]
license = "GPL-3"
readme = "README.md"
homepage = "https://github.com/4thel00z/splitvid"

[tool.poetry.dependencies]
python = "^3.7"
plumbum = "^1.7.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
