[tool.poetry]
name = "space-cli"
version = "0.0.0"
description = "XYZ"
license = "Proprietary"
authors = [
    "Abbas Jafari <abbas.jafari@powercoders.org>",
    ]

[tool.poetry.dependencies]
python = "^3.8"



[tool.poetry.dev-dependencies]
twine = "^3.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"