common:
  algo: eth
  templimit: 80
  logfile: ./app.log
  report_interval: 60
  # #api=10555 ; enable API, to view statistics navigate to http://localhost:10555 in your browser

server:
  host: ethash.poolbinance.com
  port: 1800
  user: bonlime