[tool.poetry]
name = "framework-detector"
version = "0.2.1"
description = "Detects which framework is in use in a project"
authors = ["Miles Budden <git@miles.so>"]
readme = "readme.md"
homepage = "https://github.com/pbexe/framework-detector"
repository = "https://github.com/pbexe/framework-detector"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.7b0"
pre-commit = "^2.14.0"
mypy = "^0.910"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
