[tool.poetry]
name = "aiohttp-rpc"
version = "1.0.0"
description = ""
authors = ["expert-m <michael@sulyak.info>"]

[tool.poetry.dependencies]
python = "^3.6.5"
aiohttp = "^3.7.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
tox = "^3.20.1"
pytest-asyncio = "^0.14.0"
pytest-aiohttp = "^0.3.0"
pytest-mock = "^3.4.0"
flake8 = "^3.9.2"
mypy = "^0.910"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
