[easyIntelligence]
name = "easyIntelligence"
version = "1.2.0"
description = "easyIntelligence is the next easy-to-use machine learning framework."
authors = [
    "Password-Classified"
]
license = "LICENSE"
readme = "README.md"
python = "^3.6"
homepage = "https://github.com/Password-Classified/easyIntelligence"
repository = "https://github.com/Password-Classified/easyIntelligence"
documentation = "https://github.com/Password-Classified/easyIntelligence"

keywords = ["packaging", "dependency", "infer", "pyproject.toml"]

classifiers = [
    "TOPIC :: SCIENTIFIC/ENGINEERING :: ARTIFICIAL INTELLIGENCE",
    "TOPIC :: SCIENTIFIC/ENGINEERING :: MATHEMATICS"
]

# Requirements
[dependencies]
Click = "^7.0"

[build-system]
requires = [
    "setuptools >= 35.0.2",
    "wheel",
    "copy",
    "csv",
    "math",
    "os",
    "pickle",
    "random",
    "sys",
    "decimal",
    "pprint",
    "timeit"
]
build-backend = "setuptools.build_meta"