name: tests

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Get the code:
      - uses: actions/checkout@v2
      # Run the local action:
      - uses: ./.github/actions/pytest-automation
        with:
          PYTEST_OPTIONS: -n auto
