[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fastasyncapi"
authors = [{name = "Mohsen Mahmoodi", email = "m.mahmoodi.biz@gmail.com"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://fastasyncapi.github.io"
