class DocTypeError(Exception): ...

class KeywordAttrsError(Exception): ...

class MoreNodesFound(Exception): ...

class NotNodeFound(Exception): ...

class TextNotFound(Exception): ...

class UpdateError(Exception): ...

class AddNodeError(Exception): ...

class PopError(Exception): ...