[tool.poetry]
name = "pyshmht3"
version = "0.1.1"
description = "python share memory dict for py3"
authors = ["muyakongali <muyakongali@tencent.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
