[tool.poetry]
name = "tpm"
version = "0.1.0"
description = "a cli app"
authors = ["Sayam.py"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
setuptools = "^57.4.0"
pip = "^21.2.4"
twine = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
