"""
    The api of the tek ekg boxes and field controller.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gewv_sides_client
from gewv_sides_client.model.energy_type import EnergyType
globals()['EnergyType'] = EnergyType
from gewv_sides_client.model.box_prototype import BoxPrototype


class TestBoxPrototype(unittest.TestCase):
    """BoxPrototype unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoxPrototype(self):
        """Test BoxPrototype"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BoxPrototype()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
