[tool.poetry]
name = "PyOngc"
version = "0.5.1"
description = "Python interface to OpenNGC database data."
authors = ["Mattia Verga <mattia.verga@tiscali.it>"]
license = "MIT"
readme = "README.rst"
repository = 'https://github.com/mattiaverga/PyOngc'
documentation = 'https://pyongc.readthedocs.io/en/latest/'
keywords = ['astronomy', 'database', 'ngc']
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Topic :: Database',
    'Topic :: Scientific/Engineering :: Astronomy'
]
packages = [
    { include = "pyongc" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.scripts]
ongc = 'pyongc.scripts.ongc:cli'

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
numpy = "^1.17.4"
flake8 = { version = "^3.7.9", optional = true }
mock = { version = "^3.0.5", optional = true }
pytest = { version = "^5.3.2", optional = true }

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mock = "^3.0.5"
pytest = "^5.3.2"
sphinx = "^2.3.0"
sphinx-rtd-theme = "^0.4.3"

[tool.poetry.extras]
tests = [
    "flake8",
    "mock",
    "pytest"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
