
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-17T14:33:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5768624e01222c4756acf74a856d0bad7cf5253",
 "version": "2522"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
