[tool.poetry]
name = "eagers"
version = "0.3.10"
description = "Efficient Allocation of Grid Energy Resources including Storage"
authors = ["Dustin McLarty <dustin.mclarty@wsu.edu>"]
license = "MIT"
include = ["demo_files"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "^1.21.1"
scipy = "^1.7.0"
tables = "^3.6.1"
openpyxl = "^3.0.7"
ecos = "^2.0.7"
matplotlib = "^3.4.2"
requests = "^2.26.0"
building-plus = {version = "^0.1.2", optional = true}

[tool.poetry.extras]
building-plus = ["building-plus"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.7b0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = "test"
# Use single quotes for "raw" strings in TOML.
filterwarnings = [
    'ignore:`np\.\w+` is a deprecated alias for [` \w]+\.:DeprecationWarning',
]
