
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-19T10:20:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "487c3ddf67fa7de6fb27786f0df2ba892e3529b5",
 "version": "0.4.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
