[tool.poetry]
name = "pycanister"
version = "0.1.0"
description = "PyCanister loads data from json, yaml and other file formats into classes."
authors = ["Jason Viloria <jnvilo@gmail.com>"]
license = "GPL V3"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
