[tool.poetry]
name = "kada-random-quote-generator"
version = "0.1.4"
description = "Randomly generate programming wisdom quote."
authors = ["Kada Liao <kadaliao@gmail.com>"]
packages = [
  { include = "random_quote_generator" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = "^21.7b0"
isort = "^5.9.3"
flake8 = "^3.9.2"
bandit = "^1.7.0"
safety = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
