[tool.poetry]
name = "twentyc.rpc"
repository = "https://github.com/20c/twentyc.rpc"
readme = "README.md"
version = "1.0.0"
description = "client for 20c's RESTful API"
authors = [ "20C <code@20c.com>",]
license = "LICENSE"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]

packages = [
    { include = "twentyc", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
requests = ">=2.10.0"

[tool.poetry.dev-dependencies]
# testing
codecov = ">=2.0.5,<3"
coverage = ">=4.1,<5"
pytest = "^6.0.1"
pytest-cov = "*"

# linting
black = { version = ">=20", allow-prereleases = true }
isort = "^5.7.0"
flake8 = "^3.8.4"
mypy = "^0.812"
pre-commit = "^2.13"
pyupgrade = "^2.19.4"

# docs
markdown = "*"
markdown-include = ">=0.5,<1"
mkdocs = ">=1.0.0,<2.0.0"

# ctl
ctl = "^1"
jinja2 = "^2.11.2"
tmpl = "^1"
twine = "^3.3.0"

[tool.poetry.plugins."markdown.extensions"]
pymdgen = "pymdgen.md:Extension"

[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3