[tool.poetry]
name = "execution-controller"
version = "0"
description = "Модуль инструментов для контроля процесса выполнения python программы"
authors = ["rocshers <prog.rocshers@gmail.com>"]
readme = "readme.md"
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
license = "MIT"
packages = [
    { include = "execution_controller" }
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"
mypy = "0.812"
mypy-extensions = "0.4.3"
twine = "3.4.1"
wheel = "0.36.2"
wemake-python-styleguide = "0.15.2"
autopep8 = "1.5.7"

[tool.poetry-version-plugin]
source = "git-tag"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
