[build-system]
build-backend = "enscons.api"
requires = ["pytoml>=0.1", "enscons>=0.23"]

[tool.enscons]
author = "Daniel Holth"
author_email = "dholth@fastmail.fm"
classifiers = [
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
]
description = "Tools for building Python packages with SCons"
description_file = "README.rst"
install_requires = [
  "scons>=3.0.5",
  "pytoml>=0.1",
  "setuptools",
  "wheel",
  "attrs",
  "packaging>=20.9",
  "editables==0.2;python_version>'3.0'",
]
keywords = ["packaging", "wheel"]
license = "MIT"
name = "enscons"
packages = ["enscons"]
src_root = "."
url = "https://github.com/dholth/enscons"
version = "0.28.0"

[tool.enscons.entry_points]
console_scripts = ["setup2toml = enscons.setup2toml:main"]

[tool.enscons.extras_require]
cli = ["click"]
doc = ["sphinx"]
