[tool.poetry]
name = "pyexeqjy"
version = "0.1.0"
description = "This is a cli for developer of remote vehicle side"
authors = ["qiujingyu <qiujingyu@momenta.ai>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pyexeqjy = 'pyexeqjy:entry.main'