[tool.poetry]
name = "bookscripter"
version = "0.1.0"
description = "Tools for grabbing books from Library Genesis (Libgen)."
authors = ["fitzy1293 <fitzy1293@gmail.com>"]
license = "GNU Affero General Public License v3.0"

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.2"

[tool.poetry.scripts]
bookscripter = 'bookscripter:main'

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
