[tool.poetry]
name = "tg-bw-helper"
version = "1.0.0"
description = "Thorgate helper for ansible vault password"
authors = ["Sergey Kovalskiy <sergey@thorgate.eu>"]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.4.2"

[tool.poetry.dev-dependencies]
pytest = "6.2.4"
coverage = "5.5"
prospector = ">=1.3.1"
black = "21.4b2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic = true
force_alphabetical_sort_within_sections = true
include_trailing_comma = true
known_pytest = "pytest"
# 120 is a random number that doesn't mean anything, it was picked because it was used in other project,
# where it was known to make people happy
line_length = 120
lines_after_imports = 2
multi_line_output = 3
sections = "FUTURE,STDLIB,PYTEST,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
use_parentheses = true

[tool.black]
line-length = 120

[tool.pytest.ini_options]
python_files="tests.py test_*.py *_tests.py"

[tool.tox]
legacy_tox_ini = """

[tox]
isolated_build = true
envlist = py{38,39}

[testenv]
allowlist_externals  =
    make
    poetry
setenv =
    POETRY_VIRTUALENVS_CREATE=0
commands =
    poetry install
    make test

[testenv:py38]
commands =
    poetry install
    make quality
    make coverage
"""
