[tool.poetry]
name = "dj-annotatable-field"
version = "0.1.0"
description = ""
authors = ["massover <joshm@simplebet.io>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.2.6"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-django = "*"
black = "*"
isort = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--ds=tests.settings --durations=25 --reuse-db -vv --no-migrations"

[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.circleci
    | \.git
    | \.github
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | staticfiles
    | media
  )/
  | code_sample.py
)
'''

[tool.isort]
force_single_line = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip = ["venv", ".venv", "media", "staticfiles"]

[tool.coverage.run]
omit = [
    "*/migrations/*",
    "manage.py",
    "tests/urls.py",
]
