[tool.poetry]
name = "numuse"
version = "0.1.2"
description = "Music experimentation library"
authors = ["ccn <ccn@cuppajoeman.com>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://gitlab.com/cuppajoeman/numuse"
repository = "https://gitlab.com/cuppajoeman/numuse"
documentation = "https://numuse.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
insegel = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
