[tool.poetry]
name = "bunnyApi"
version = "0.1.1"
description = "bunny.net API client"
authors = ["Andy 'danjo' Jacobsen <atze.danjo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
