[build-system]
# Minimum requirements for the build system to execute.
requires = [
    'setuptools >=49.6.0',
'wheel >=0.36.2',
'sage-setup',
'cython >=0.29.21, <1.0',
]
build-backend = "setuptools.build_meta"
