[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["alectryon"]
reportOptionalMemberAccess = false
reportWildcardImportFromLibrary = false

[tool.mypy]
ignore_missing_imports = true
