[tool.poetry]
name = "dq-tool-bundle"
version = "0.0.4"
description = "DQ Tool for the Daipe AI Platform"
readme = "README.md"
repository = "https://github.com/daipe-ai/dq-tool-bundle"

license = "MIT"

authors = [
    "DataSentics <info@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "dqtoolbundle", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
ipython = "7.12.0"
pyfony-bundles = "0.4.*"
dq-tool = "~0.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.0"
black = "^20.8b1"
flake8-fixme = "^1.1.1"
pep8-naming = "^0.11.1"
poethepoet = "^0.10.0"
pyfony-core = "0.8.*"
pyspark = "^3.1.1"

[[tool.poetry.source]]
name = "datasentics"
url = "https://pkgs.dev.azure.com/dataengineerics/_packaging/dataengineerics/pypi/simple/"
secondary = true

[tool.poetry.plugins."pyfony.bundle"]
create = "dqtoolbundle.DQToolBundle:DQToolBundle"

[pyfony.bootstrap]
container_init = "pyfonycore.container.container_init:init_with_current_bundle"
root_module_name = "dqtoolbundle"

[tool.black]
line-length = 140

[tool.poe.tasks]
black = "black src"
black-check = "black --check src"
flake8 = "flake8 --ignore=E501,W503 src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
