[tool.poetry]
name = "parse_audits"
version = "2.6.3"
description = "A library and tool to parse ClearQuest AuditTrail files to an easier-to-use format."
authors = ["harmony5 <jeancgo@pm.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/harmony5/parse_audits"
homepage = "https://github.com/harmony5/parse_audits"
packages = [
    { include = "src/parse_audits" },
    { include = "src/bin" },
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.1"
typer = {extras = ["all"], version = "^0.3.2"}
regex = "^2021.8.3"

[tool.poetry.dev-dependencies]
openpyxl = "^3.0.7"

[tool.poetry.scripts]
parse-audits = "bin.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/harmony5/parse_audits/issues"
