[tool.poetry]
name = "bigquery-dry-run"
version = "0.3.1"
description = "This package is used to perform a BigQuery dry run of all `.sql` files in a folder and its subfolders."
readme = "README.md"
keywords = ["bigquery"]
license = "MIT"
authors = ["Christo Olivier <mail@christoolivier.com>"]

[tool.poetry.dependencies]
python = "^3.6,<3.10"
pytz = "^2021.1"
google-cloud-bigquery = "^2.13.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bqdry = "bigquery_dry_run.app:run"