# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'point.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 282)
        Dialog.setMinimumSize(QtCore.QSize(350, 219))
        Dialog.setMaximumSize(QtCore.QSize(350, 500))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(328, 125))
        self.groupBox.setMaximumSize(QtCore.QSize(328, 125))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("color: rgb(170, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_x.setDecimals(6)
        self.doubleSpinBox_x.setMinimum(-999999.0)
        self.doubleSpinBox_x.setMaximum(999999.0)
        self.doubleSpinBox_x.setSingleStep(1.0)
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.gridLayout.addWidget(self.doubleSpinBox_x, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("color: rgb(170, 255, 255);")
        self.label_3.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_y.setDecimals(6)
        self.doubleSpinBox_y.setMinimum(-999999.0)
        self.doubleSpinBox_y.setMaximum(999999.0)
        self.doubleSpinBox_y.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.gridLayout.addWidget(self.doubleSpinBox_y, 1, 1, 1, 1)
        self.doubleSpinBox_z = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_z.setDecimals(6)
        self.doubleSpinBox_z.setMinimum(-999999.0)
        self.doubleSpinBox_z.setMaximum(999999.0)
        self.doubleSpinBox_z.setObjectName("doubleSpinBox_z")
        self.gridLayout.addWidget(self.doubleSpinBox_z, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.checkBox_onwire = QtWidgets.QCheckBox(Dialog)
        self.checkBox_onwire.setObjectName("checkBox_onwire")
        self.horizontalLayout_2.addWidget(self.checkBox_onwire)
        self.checkBox_center = QtWidgets.QCheckBox(Dialog)
        self.checkBox_center.setObjectName("checkBox_center")
        self.horizontalLayout_2.addWidget(self.checkBox_center)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setAutoDefault(False)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_reset = QtWidgets.QPushButton(self.frame)
        self.pushButton_reset.setAutoDefault(False)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout.addWidget(self.pushButton_reset)
        self.pushButton_app = QtWidgets.QPushButton(self.frame)
        self.pushButton_app.setAutoDefault(False)
        self.pushButton_app.setObjectName("pushButton_app")
        self.horizontalLayout.addWidget(self.pushButton_app)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "点"))
        self.groupBox.setTitle(_translate("Dialog", "坐标"))
        self.label.setText(_translate("Dialog", "X"))
        self.label_2.setText(_translate("Dialog", "Y"))
        self.label_3.setText(_translate("Dialog", "Z"))
        self.checkBox_onwire.setText(_translate("Dialog", "在线上"))
        self.checkBox_center.setText(_translate("Dialog", "圆心"))
        self.pushButton_ok.setText(_translate("Dialog", "确定"))
        self.pushButton_reset.setText(_translate("Dialog", "重置"))
        self.pushButton_app.setText(_translate("Dialog", "应用"))
