# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 283)
        Dialog.setMinimumSize(QtCore.QSize(350, 219))
        Dialog.setMaximumSize(QtCore.QSize(350, 1000))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.commandLinkButton_start = QtWidgets.QCommandLinkButton(self.groupBox_3)
        self.commandLinkButton_start.setAutoDefault(False)
        self.commandLinkButton_start.setObjectName("commandLinkButton_start")
        self.horizontalLayout_3.addWidget(self.commandLinkButton_start)
        self.commandLinkButton_stop = QtWidgets.QCommandLinkButton(self.groupBox_3)
        self.commandLinkButton_stop.setAutoDefault(False)
        self.commandLinkButton_stop.setObjectName("commandLinkButton_stop")
        self.horizontalLayout_3.addWidget(self.commandLinkButton_stop)
        self.checkBox_fix = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_fix.setObjectName("checkBox_fix")
        self.horizontalLayout_3.addWidget(self.checkBox_fix)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalSlider_sudu = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_sudu.setMaximum(240)
        self.horizontalSlider_sudu.setSingleStep(1)
        self.horizontalSlider_sudu.setPageStep(10)
        self.horizontalSlider_sudu.setProperty("value", 120)
        self.horizontalSlider_sudu.setSliderPosition(120)
        self.horizontalSlider_sudu.setTracking(True)
        self.horizontalSlider_sudu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sudu.setInvertedAppearance(False)
        self.horizontalSlider_sudu.setInvertedControls(False)
        self.horizontalSlider_sudu.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_sudu.setTickInterval(0)
        self.horizontalSlider_sudu.setObjectName("horizontalSlider_sudu")
        self.horizontalLayout.addWidget(self.horizontalSlider_sudu)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_jindu = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_jindu.setMaximum(100)
        self.horizontalSlider_jindu.setSingleStep(1)
        self.horizontalSlider_jindu.setPageStep(1)
        self.horizontalSlider_jindu.setProperty("value", 0)
        self.horizontalSlider_jindu.setSliderPosition(0)
        self.horizontalSlider_jindu.setTracking(True)
        self.horizontalSlider_jindu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_jindu.setInvertedAppearance(False)
        self.horizontalSlider_jindu.setInvertedControls(False)
        self.horizontalSlider_jindu.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_jindu.setTickInterval(0)
        self.horizontalSlider_jindu.setObjectName("horizontalSlider_jindu")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_jindu)
        self.label_jindu = QtWidgets.QLabel(self.groupBox)
        self.label_jindu.setObjectName("label_jindu")
        self.horizontalLayout_2.addWidget(self.label_jindu)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "路劲运动"))
        self.groupBox_3.setTitle(_translate("Dialog", "功能"))
        self.commandLinkButton_start.setText(_translate("Dialog", "开始"))
        self.commandLinkButton_stop.setText(_translate("Dialog", "暂停"))
        self.checkBox_fix.setText(_translate("Dialog", "固定工具"))
        self.label.setText(_translate("Dialog", "速度: "))
        self.label_2.setText(_translate("Dialog", "快"))
        self.label_3.setText(_translate("Dialog", "慢"))
        self.groupBox.setTitle(_translate("Dialog", "进度"))
        self.label_jindu.setText(_translate("Dialog", "0%"))
