
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8b6e1f3750e201e5834d8782c5ad0dda6a928e1d",
 "version": "0.30.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
