repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "371a07eb4c7458db469e9a96382309c19312de6b"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hakancelik96/unimport
    rev: fdf31b7940133f0a5307a767b6485d344ac2007b
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]
  - repo: https://github.com/pycqa/isort
    rev: "cd6b09c07c20a47cfab26a1aa93a37be1c57bb22"
    hooks:
      - id: isort
        files: "gdsfactory/.*"
        args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: 2b2f0c74acdb3de316e23ceb7dd0d7945c354050
  #   hooks:
  #     - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: "519f807f879350704449e424c5c5b7e049e582b3"
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3bcadce2a9d91f4bb6afa97b5d2d1a82d7a1e937"
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: b6da9bfa630e7570fe909fd51091a75d4d01236a
    hooks:
      - id: nbstripout
        files: ".ipynb"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "214c33306afe17f1cc7d2d55e4da705b6ebe0627"
  #   hooks:
  #     - id: mypy
  #       exclude: ^(docs/|example-plugin/|tests/fixtures)
  #       additional_dependencies:
  #         - "pydantic"

  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #       - id: darglint
  #
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: ""
  #   hooks:
  #       - id: pydocstyle
