# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wire_rotate_edit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 265)
        Dialog.setMinimumSize(QtCore.QSize(350, 219))
        Dialog.setMaximumSize(QtCore.QSize(350, 1000))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(328, 160))
        self.groupBox.setMaximumSize(QtCore.QSize(328, 160))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_x = QtWidgets.QLabel(self.groupBox)
        self.label_x.setMinimumSize(QtCore.QSize(65, 0))
        self.label_x.setStyleSheet("")
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doubleSpinBox_angle = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_angle.setDecimals(6)
        self.doubleSpinBox_angle.setMinimum(-360.0)
        self.doubleSpinBox_angle.setMaximum(360.0)
        self.doubleSpinBox_angle.setObjectName("doubleSpinBox_angle")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_angle)
        self.pushButton_2point = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2point.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_2point.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_2point.setCheckable(True)
        self.pushButton_2point.setAutoDefault(False)
        self.pushButton_2point.setObjectName("pushButton_2point")
        self.horizontalLayout_3.addWidget(self.pushButton_2point)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_x = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_x.setObjectName("checkBox_x")
        self.horizontalLayout_2.addWidget(self.checkBox_x)
        self.checkBox_y = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_y.setObjectName("checkBox_y")
        self.horizontalLayout_2.addWidget(self.checkBox_y)
        self.checkBox_z = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_z.setTristate(False)
        self.checkBox_z.setObjectName("checkBox_z")
        self.horizontalLayout_2.addWidget(self.checkBox_z)
        self.checkBox_view = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_view.setObjectName("checkBox_view")
        self.horizontalLayout_2.addWidget(self.checkBox_view)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_point = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_point.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_point.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_point.setCursorPosition(0)
        self.lineEdit_point.setReadOnly(False)
        self.lineEdit_point.setClearButtonEnabled(True)
        self.lineEdit_point.setObjectName("lineEdit_point")
        self.horizontalLayout_4.addWidget(self.lineEdit_point)
        self.pushButton_3point = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3point.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_3point.setCheckable(True)
        self.pushButton_3point.setAutoDefault(False)
        self.pushButton_3point.setObjectName("pushButton_3point")
        self.horizontalLayout_4.addWidget(self.pushButton_3point)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_y = QtWidgets.QLabel(self.groupBox)
        self.label_y.setStyleSheet("")
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 2, 0, 1, 1)
        self.label_z = QtWidgets.QLabel(self.groupBox)
        self.label_z.setStyleSheet("")
        self.label_z.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.label_z.setObjectName("label_z")
        self.gridLayout.addWidget(self.label_z, 3, 0, 1, 1)
        self.label_x_2 = QtWidgets.QLabel(self.groupBox)
        self.label_x_2.setMinimumSize(QtCore.QSize(65, 0))
        self.label_x_2.setStyleSheet("")
        self.label_x_2.setObjectName("label_x_2")
        self.gridLayout.addWidget(self.label_x_2, 0, 0, 1, 1)
        self.lineEdit_wire = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_wire.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_wire.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_wire.setCursorPosition(0)
        self.lineEdit_wire.setReadOnly(False)
        self.lineEdit_wire.setClearButtonEnabled(True)
        self.lineEdit_wire.setObjectName("lineEdit_wire")
        self.gridLayout.addWidget(self.lineEdit_wire, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setAutoDefault(False)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_reset = QtWidgets.QPushButton(self.frame)
        self.pushButton_reset.setAutoDefault(False)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout.addWidget(self.pushButton_reset)
        self.pushButton_app = QtWidgets.QPushButton(self.frame)
        self.pushButton_app.setAutoDefault(False)
        self.pushButton_app.setObjectName("pushButton_app")
        self.horizontalLayout.addWidget(self.pushButton_app)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_wire, self.lineEdit_point)
        Dialog.setTabOrder(self.lineEdit_point, self.doubleSpinBox_angle)
        Dialog.setTabOrder(self.doubleSpinBox_angle, self.checkBox_x)
        Dialog.setTabOrder(self.checkBox_x, self.checkBox_y)
        Dialog.setTabOrder(self.checkBox_y, self.checkBox_z)
        Dialog.setTabOrder(self.checkBox_z, self.checkBox_view)
        Dialog.setTabOrder(self.checkBox_view, self.pushButton_3point)
        Dialog.setTabOrder(self.pushButton_3point, self.pushButton_2point)
        Dialog.setTabOrder(self.pushButton_2point, self.pushButton_ok)
        Dialog.setTabOrder(self.pushButton_ok, self.pushButton_reset)
        Dialog.setTabOrder(self.pushButton_reset, self.pushButton_app)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "路径旋转"))
        self.groupBox.setTitle(_translate("Dialog", "旋转"))
        self.label_x.setText(_translate("Dialog", "中心点"))
        self.pushButton_2point.setText(_translate("Dialog", "俩点测量"))
        self.checkBox_x.setText(_translate("Dialog", "X"))
        self.checkBox_y.setText(_translate("Dialog", "Y"))
        self.checkBox_z.setText(_translate("Dialog", "Z"))
        self.checkBox_view.setText(_translate("Dialog", "视图"))
        self.pushButton_3point.setText(_translate("Dialog", "三点测量"))
        self.label_y.setText(_translate("Dialog", "旋转轴"))
        self.label_z.setText(_translate("Dialog", "角度"))
        self.label_x_2.setText(_translate("Dialog", "轮廓线"))
        self.pushButton_ok.setText(_translate("Dialog", "确定"))
        self.pushButton_reset.setText(_translate("Dialog", "重置"))
        self.pushButton_app.setText(_translate("Dialog", "应用"))
