[tool.poetry]
name = "qft"
version = "0.0.2"
description = ""
authors = ["Scott Lawrence <scott.lawrence-1@colorado.edu>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
