[tool.poetry]
name = "sundial-framework"
version = "0.1.0"
description = ""
authors = ["Gavin Bell <gavin.bell@optimeering.com>"]
license = "Apache-2.0"
packages = [
    {include = "sundial"}
]

[tool.black]
line-length = 120
target_version = ['py38']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files

known_third_party = ["archimedes", "holidays", "icecream", "matplotlib", "numpy", "pandas", "plotly", "setuptools", "sklearn", "tensorflow"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.17.99"
click = "7.1.2"
coverage = "^5.5"
flake8 = "^3.9.2"
python-dotenv = "^0.18.0"
tensorflow = "2.2.0"
notebook = "^6.4.0"
streamlit = "^0.83.0"
mlflow = "^1.18.0"
sklearn = "^0.0"
pandas = "^1.2.5"
archimedes-python-client = "^2.2.4"
pytest = "^6.2.4"
dash = "^1.20.0"
holidays = "^0.11.1"
icecream = "^2.1.1"

[tool.poetry.dev-dependencies]
isort = "^5.8.0"
black = "^21.6b0"
pytest = "^6.2.4"
pre-commit = "^2.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
