[tool.poetry]
name = "tamarin"
version = "0.15.1"
description = "Lamasoo utils for developing web application"
authors = ["alirezainfotech <alireza.infotech@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.3"
requests = "^2.25.1"
django-rest-framework = "^0.1.0"
elasticsearch = "^7.12.1"
celery = "^5.1.0"
sentry-sdk = "^1.1.0"
setuptools = "^57.0.0"
wheel = "^0.36.2"
python-dateutil = "^2.8.1"
django-push-notifications = "^2.0.0"
jose = "^1.0.0"
python-jose = "^3.2.0"
pycryptodome = "^3.10.1"
djangorestframework-simplejwt = "^4.7.0"
firebase-admin = "^5.0.0"
google-api-python-client = "^2.5.0"
django-nose = "^1.4.7"
twine = "^3.4.1"
python-telegram-bot = "^13.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
