[tool.poetry]
name = "streamlit_kpi_metric"
version = "0.1.0"
description = "Library to create KPI metric for streamlit dashboards"
authors = ["100mi <smtrgupta96@gmail.com>"]
readme = "README.md"
keywords = ["streamlit", "kpi", "metrics"]

[tool.poetry.dependencies]
python = "^3.9"
streamlit = "^0.86.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"