[tool.poetry]
name = "modrs"
version = "0.3.0-beta.1"
description = "A Python module wirtten in Rust"
authors = ["Nagendra_2k3 <71603665+nv2k3@users.noreply.github.com>"]
dependencies={python = "^3.6"}
dev-dependencies={maturin = "==0.11.2"}

[build-system]
requires = ["maturin>=0.10,<0.11"]
build-backend = "maturin"

[project]
name="modrs"
scripts={aaa="modrs:_cli"}
